# Generated by Django 2.2.1 on 2019-10-19 08:10

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '博客分类',
                'verbose_name_plural': '博客分类',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '标签名称',
                'verbose_name_plural': '标签名称',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('pic', models.ImageField(blank=True, default='blog_pic/book1.jpg', upload_to='blog_pic/%Y%m%d/', verbose_name='博客封面图片')),
                ('html', models.TextField(editable=False)),
                ('toc', models.TextField(blank=True, editable=False)),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='更改日期')),
                ('read_num', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog.Category', verbose_name='类别名称')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='blog.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-publish_time'],
            },
        ),
    ]
