# Generated by Django 2.2.1 on 2019-10-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191020_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
