# Generated by Django 2.2.1 on 2019-10-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191020_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='article_count',
            field=models.PositiveIntegerField(default=0, verbose_name='文章数'),
        ),
    ]
