# Generated by Django 2.2.1 on 2019-10-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_article_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='toc',
            field=models.TextField(editable=False),
        ),
    ]
