# Generated by Django 2.2.1 on 2019-11-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191030_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='html_content',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='toc',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
