# Generated by Django 2.2.1 on 2019-11-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191106_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.ImageField(blank=True, default='blog_pic/book.jpg', upload_to='blog_pic/%Y%m%d/', verbose_name='博客封面图片'),
        ),
    ]
